import { UserProfile, Post, Story, Conversation, AppNotification, ReelItem, InstantItem } from './types';

export const SEED_USERS: UserProfile[] = [
  {
    id: 'user-mujeeb',
    username: 'mujee00012',
    displayName: 'Mujeeb Rahman',
    email: 'mujee00012@gmail.com',
    avatarUrl: '/images/avatar-mujeeb.png',
    bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    bio: 'Visual creator on Lumira ✦ Connected via Google Account\nKerala, India',
    website: 'https://lumir-a.vercel.app',
    location: 'Kerala, India',
    pronouns: 'he/him',
    isVerified: true,
    isAdmin: false,
    role: 'user',
    isPrivate: false,
    followersCount: 120,
    followingCount: 15,
    postsCount: 0,
    followers: ['user-hisham', 'user-admin', 'user-elena'],
    following: ['user-hisham', 'user-admin'],
    createdAt: '2025-01-01T00:00:00Z',
    themePreference: 'dark',
  },
  {
    id: 'user-hisham',
    username: 'mhudhishamp',
    displayName: 'Muhammed Hisham',
    email: 'mhudhishamp@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    bio: 'Creative Developer & Designer ✦ Lumira Community\nKerala, India',
    website: 'https://lumir-a.vercel.app',
    location: 'Kerala, India',
    pronouns: 'he/him',
    isVerified: true,
    isAdmin: false,
    role: 'user',
    isPrivate: false,
    followersCount: 95,
    followingCount: 12,
    postsCount: 0,
    followers: ['user-mujeeb', 'user-admin'],
    following: ['user-mujeeb', 'user-admin'],
    createdAt: '2025-01-02T00:00:00Z',
    themePreference: 'dark',
  },
  {
    id: 'user-admin',
    username: 'admin',
    displayName: 'Super Admin',
    email: 'admin@lumira.app',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    bio: 'Official Lumira Super Admin 🛡️ \nPlatform Safety & Governance \nContact: admin@lumira.app',
    website: 'https://lumira.app',
    location: 'Headquarters',
    pronouns: 'they/them',
    isVerified: true,
    isAdmin: true,
    role: 'admin',
    isPrivate: false,
    followersCount: 150000,
    followingCount: 12,
    postsCount: 12,
    followers: ['user-elena', 'user-marcus', 'user-aria', 'user-kai', 'user-maya', 'user-mujeeb', 'user-hisham'],
    following: ['user-elena', 'user-marcus', 'user-aria'],
    createdAt: '2024-01-01T00:00:00Z',
    themePreference: 'dark',
  },
  {
    id: 'user-elena',
    username: 'elena.vance',
    displayName: 'Elena Vance',
    email: 'elena@lumira.app',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    bio: 'Visual artist & creative director 📸 \nTokyo • San Francisco \nInquiries: contact@elenavance.co',
    website: 'https://elenavance.co',
    location: 'Tokyo, Japan',
    pronouns: 'she/her',
    isVerified: true,
    isPrivate: false,
    followersCount: 48200,
    followingCount: 382,
    postsCount: 38,
    followers: ['user-marcus', 'user-aria', 'user-kai', 'user-maya'],
    following: ['user-marcus', 'user-aria', 'user-kai', 'user-maya', 'user-leo', 'user-chloe'],
    createdAt: '2025-01-15T08:00:00Z',
    themePreference: 'light',
  },
  {
    id: 'user-marcus',
    username: 'marcus.thorne',
    displayName: 'Marcus Thorne',
    email: 'marcus@lumira.app',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    bio: 'Architecture & Street Photography 🏛️ \nBerlin | Hasselblad Master \nNew book “Shadows & Steel” out now ↓',
    website: 'https://thorne.photo',
    location: 'Berlin, Germany',
    pronouns: 'he/him',
    isVerified: true,
    isPrivate: false,
    followersCount: 89400,
    followingCount: 412,
    postsCount: 92,
    followers: ['user-elena', 'user-aria', 'user-maya'],
    following: ['user-elena', 'user-kai', 'user-chloe'],
    createdAt: '2024-11-20T10:30:00Z',
    themePreference: 'dark',
  },
  {
    id: 'user-aria',
    username: 'aria.chen',
    displayName: 'Aria Chen',
    email: 'aria@lumira.app',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    bio: 'Sound designer & synth enthusiast 🎹 \nSF Bay Area \nListen to my latest track on Spotify 🎧',
    website: 'https://ariachen.tech',
    location: 'San Francisco, CA',
    pronouns: 'they/them',
    isVerified: true,
    isPrivate: false,
    followersCount: 24500,
    followingCount: 290,
    postsCount: 45,
    followers: ['user-elena', 'user-marcus', 'user-kai'],
    following: ['user-elena', 'user-marcus', 'user-maya'],
    createdAt: '2025-02-01T14:15:00Z',
    themePreference: 'dark',
  },
  {
    id: 'user-kai',
    username: 'kai.rivera',
    displayName: 'Kai Rivera',
    email: 'kai@lumira.app',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    bio: 'Big wave surfer & filmmaker 🌊 \nLisbon ✈️ Hawaii \nChasing Atlantic swells all winter 🏄‍♂️',
    website: 'https://riverafilms.io',
    location: 'Lisbon, Portugal',
    pronouns: 'he/him',
    isVerified: false,
    isPrivate: false,
    followersCount: 54100,
    followingCount: 520,
    postsCount: 68,
    followers: ['user-elena', 'user-marcus', 'user-aria'],
    following: ['user-elena', 'user-marcus', 'user-aria', 'user-maya'],
    createdAt: '2024-09-10T12:00:00Z',
    themePreference: 'light',
  },
  {
    id: 'user-maya',
    username: 'maya.lin',
    displayName: 'Maya Lin',
    email: 'maya@lumira.app',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1200&q=80',
    bio: 'Ceramic Studio & Minimalist Interiors 🏺 \nCopenhagen \nNext collection drops Friday 10am CET',
    website: 'https://mayalinstudio.co',
    location: 'Copenhagen, Denmark',
    pronouns: 'she/her',
    isVerified: true,
    isPrivate: false,
    followersCount: 63200,
    followingCount: 310,
    postsCount: 114,
    followers: ['user-elena', 'user-kai'],
    following: ['user-elena', 'user-marcus'],
    createdAt: '2024-08-01T09:00:00Z',
    themePreference: 'light',
  },
  {
    id: 'user-leo',
    username: 'leo.rossi',
    displayName: 'Leo Rossi',
    email: 'leo@lumira.app',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    bio: 'Digital artist & Motion Designer 🌌 \nMilano, Italia \nPrints available worldwide',
    website: 'https://leorossi.xyz',
    location: 'Milan, Italy',
    isVerified: false,
    isPrivate: false,
    followersCount: 19800,
    followingCount: 180,
    postsCount: 29,
    followers: ['user-elena'],
    following: ['user-elena', 'user-marcus'],
    createdAt: '2025-03-01T11:00:00Z',
    themePreference: 'dark',
  },
  {
    id: 'user-chloe',
    username: 'chloe.dubois',
    displayName: 'Chloé Dubois',
    email: 'chloe@lumira.app',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
    bio: 'Fashion Editor & Stylist 👗 \nParis \nEditorial features for Vogue & Elle',
    website: 'https://chloedubois.paris',
    location: 'Paris, France',
    isVerified: true,
    isPrivate: false,
    followersCount: 112000,
    followingCount: 650,
    postsCount: 142,
    followers: ['user-elena', 'user-marcus'],
    following: ['user-elena', 'user-marcus'],
    createdAt: '2024-06-12T16:00:00Z',
    themePreference: 'light',
  },
];

export const SEED_POSTS: Post[] = [
  {
    id: 'post-arian-beach',
    authorId: 'user-arian',
    author: {
      id: 'user-arian',
      username: 'arian',
      displayName: 'Arian',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      isVerified: false,
    },
    media: [
      {
        id: 'mb1',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
        altText: 'Vibrant sunset over calm tropical ocean with silhouetted palm trees',
      },
      {
        id: 'mb2',
        url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
      },
      {
        id: 'mb3',
        url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
      },
    ],
    caption: 'Beautiful evening walks by the beach 🌅',
    tags: ['sunset', 'beach', 'kerala', 'travel', 'nature'],
    mentions: [],
    location: 'Kerala, India',
    audioTrack: {
      title: 'Sunset Lover',
      artist: 'Petit Biscuit',
    },
    likesCount: 1245,
    likes: ['user-mujeeb', 'user-maya', 'user-kai'],
    commentsCount: 32,
    sharesCount: 54,
    bookmarksCount: 210,
    bookmarkedBy: ['user-mujeeb'],
    allowComments: true,
    isPrivate: false,
    createdAt: '2026-08-30T10:00:00.000Z',
    pinned: true,
  },
  {
    id: 'post-maya-reel',
    authorId: 'user-maya',
    author: {
      id: 'user-maya',
      username: 'maya.singh',
      displayName: 'Maya Singh',
      avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
      isVerified: true,
    },
    isReel: true,
    media: [
      {
        id: 'mr1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
        altText: 'Girl on mountain road with wind in hair looking back',
      },
    ],
    caption: 'Mountains, mood and a little bit of wind 🌿',
    tags: ['mountains', 'mood', 'reels', 'travel', 'nature'],
    mentions: [],
    location: 'Original audio',
    audioTrack: {
      title: 'Kho Gaye Hum Kahan',
      artist: 'Jasleen Royal',
    },
    likesCount: 8765,
    likes: ['user-elena', 'user-marcus', 'user-aria', 'user-kai'],
    commentsCount: 106,
    sharesCount: 32,
    bookmarksCount: 890,
    bookmarkedBy: ['user-elena'],
    allowComments: true,
    isPrivate: false,
    createdAt: '2026-08-30T09:00:00.000Z',
  },
  {
    id: 'post-kai-london',
    authorId: 'user-kai',
    author: {
      id: 'user-kai',
      username: 'kai.carter',
      displayName: 'Kai Carter',
      avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
      isVerified: false,
    },
    media: [
      {
        id: 'ml1',
        url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
        altText: 'London Tower Bridge at golden sunset',
      },
      {
        id: 'ml2',
        url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
      },
      {
        id: 'ml3',
        url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
      },
      {
        id: 'ml4',
        url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
      },
      {
        id: 'ml5',
        url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
      },
    ],
    caption: 'Sunset over Tower Bridge. The light hitting the Thames this evening was unreal.',
    tags: ['london', 'architecture', 'city', 'travel'],
    mentions: [],
    location: 'London, United Kingdom',
    likesCount: 3420,
    likes: ['user-elena', 'user-marcus'],
    commentsCount: 42,
    sharesCount: 18,
    bookmarksCount: 320,
    bookmarkedBy: ['user-marcus'],
    allowComments: true,
    isPrivate: false,
    createdAt: '2026-08-30T08:00:00.000Z',
  },
  {
    id: 'post-1',
    authorId: 'user-elena',
    author: {
      id: 'user-elena',
      username: 'elena.vance',
      displayName: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    media: [
      {
        id: 'm1',
        url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
        altText: 'Luminous dynamic 3D glass waves in iridescent purple and turquoise',
      },
      {
        id: 'm2',
        url: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
        altText: 'Bioluminescent chromatic glass refraction sphere',
      },
    ],
    caption: 'Moments of pure light and fluid refraction in the Tokyo studio. Which color spectrum resonates most with your space? ✨🌊 Audio by @aria.chen 🎧',
    tags: ['digitalart', 'tokyo', 'design', '3drender', 'creative'],
    mentions: ['aria.chen'],
    location: 'Mori Digital Art Museum, Tokyo',
    audioTrack: {
      title: 'Neural Waves (Ambient Mix)',
      artist: 'Aria Chen x Elena Vance',
    },
    likesCount: 2842,
    likes: ['user-marcus', 'user-aria', 'user-kai', 'user-maya'],
    commentsCount: 48,
    sharesCount: 192,
    bookmarksCount: 420,
    bookmarkedBy: ['user-marcus', 'user-aria'],
    allowComments: true,
    isPrivate: false,
    createdAt: '2026-08-21T15:00:00.000Z',
    pinned: true,
  },
  {
    id: 'post-2',
    authorId: 'user-marcus',
    author: {
      id: 'user-marcus',
      username: 'marcus.thorne',
      displayName: 'Marcus Thorne',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    media: [
      {
        id: 'm4',
        url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'square',
        altText: 'Skyward angle of monolithic glass and steel modern skyscraper in black and white',
      },
      {
        id: 'm5',
        url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'square',
        altText: 'Minimalist concrete spiral stair geometry',
      },
    ],
    caption: 'Monoliths in the morning fog. When concrete meets low-hanging autumn clouds, the city dissolves into pure rhythm and geometry. Hasselblad 907X + 45mm f/4.',
    tags: ['architecture', 'minimalism', 'blackandwhite', 'berlin', 'hasselblad'],
    mentions: [],
    location: 'Potsdamer Platz, Berlin',
    likesCount: 5410,
    likes: ['user-elena', 'user-maya', 'user-chloe'],
    commentsCount: 62,
    sharesCount: 310,
    bookmarksCount: 890,
    bookmarkedBy: ['user-elena'],
    allowComments: true,
    isPrivate: false,
    createdAt: '2026-08-21T13:00:00.000Z',
  },
  {
    id: 'post-3',
    authorId: 'user-kai',
    author: {
      id: 'user-kai',
      username: 'kai.rivera',
      displayName: 'Kai Rivera',
      avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
      isVerified: false,
    },
    media: [
      {
        id: 'm6',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
        altText: 'Golden sunset over tranquil crystal teal tropical ocean shore',
      },
    ],
    caption: 'Nazaré season is right around the corner. Checking the swell charts at dawn and the energy brewing across the Atlantic is unlike anything else on earth. 🌊🔥',
    tags: ['ocean', 'surf', 'nazare', 'portugal', 'adventure'],
    mentions: ['elena.vance'],
    location: 'Nazaré, Portugal',
    likesCount: 8210,
    likes: ['user-elena', 'user-marcus', 'user-aria'],
    commentsCount: 84,
    sharesCount: 420,
    bookmarksCount: 1120,
    bookmarkedBy: ['user-elena', 'user-marcus'],
    allowComments: true,
    isPrivate: false,
    createdAt: '2026-08-21T08:00:00.000Z',
  },
  {
    id: 'post-4',
    authorId: 'user-aria',
    author: {
      id: 'user-aria',
      username: 'aria.chen',
      displayName: 'Aria Chen',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    media: [
      {
        id: 'm7',
        url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'portrait',
        altText: 'Macro photograph of high-tech glowing electronic motherboard and microchips with violet LEDs',
      },
    ],
    caption: 'Late night soldering and firmware testing for the new analog-neural synth module. 0.2ms latency achieved with real-time waveform warping! ⚡👾',
    tags: ['synthesizer', 'musictech', 'electronicmusic', 'studio'],
    mentions: [],
    location: 'Mission District, San Francisco',
    likesCount: 3290,
    likes: ['user-elena', 'user-kai'],
    commentsCount: 31,
    sharesCount: 87,
    bookmarksCount: 230,
    bookmarkedBy: ['user-elena'],
    allowComments: true,
    isPrivate: false,
    createdAt: '2026-08-20T22:00:00.000Z',
  },
  {
    id: 'post-5',
    authorId: 'user-maya',
    author: {
      id: 'user-maya',
      username: 'maya.lin',
      displayName: 'Maya Lin',
      avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    media: [
      {
        id: 'm8',
        url: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1200&q=80',
        type: 'image',
        aspectRatio: 'square',
        altText: 'Sculptural organic ceramic vase with textured sand glaze in warm sunlit studio',
      },
    ],
    caption: 'New hand-thrown vessel in terracotta with wild volcanic sand glaze. Imperfection is where the soul of the object lives. Available in tomorrow’s online drop. 🏺',
    tags: ['ceramics', 'sculpture', 'interiordesign', 'copenhagen', 'wabisabi'],
    mentions: [],
    location: 'Copenhagen, Denmark',
    likesCount: 4780,
    likes: ['user-elena', 'user-marcus', 'user-chloe'],
    commentsCount: 55,
    sharesCount: 140,
    bookmarksCount: 680,
    bookmarkedBy: ['user-elena'],
    allowComments: true,
    isPrivate: false,
    createdAt: '2026-08-20T16:00:00.000Z',
  },
];

export const SEED_REELS: ReelItem[] = [
  {
    id: 'reel-1',
    authorId: 'user-elena',
    author: {
      id: 'user-elena',
      username: 'elena.vance',
      displayName: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-set-of-plateaus-seen-from-the-sky-in-a-sunset-26070-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    caption: '48-hour fluid simulation breakdown in Tokyo 🌌 Sound on for the spatial frequencies 🎧 #reels #art #generative #tokyo',
    tags: ['reels', 'art', 'generative', 'tokyo'],
    audioTrack: {
      title: 'Neural Waves (Original Audio)',
      artist: 'elena.vance',
    },
    likesCount: 18400,
    likes: ['user-marcus', 'user-aria', 'user-kai'],
    commentsCount: 412,
    sharesCount: 2310,
    bookmarkedBy: ['user-marcus'],
    createdAt: '2026-08-21T14:00:00.000Z',
  },
  {
    id: 'reel-2',
    authorId: 'user-kai',
    author: {
      id: 'user-kai',
      username: 'kai.rivera',
      displayName: 'Kai Rivera',
      avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
      isVerified: false,
    },
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-waves-in-the-water-1164-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    caption: 'Sunset session at Supertubos. When the tide hits the sandbar just right... 🏄‍♂️🌊 #surf #reels #ocean #portugal',
    tags: ['surf', 'reels', 'ocean', 'portugal'],
    audioTrack: {
      title: 'Atlantic Breeze (Remix)',
      artist: 'kai.rivera',
    },
    likesCount: 34200,
    likes: ['user-elena', 'user-marcus'],
    commentsCount: 680,
    sharesCount: 5400,
    bookmarkedBy: ['user-elena'],
    createdAt: '2026-08-21T12:00:00.000Z',
  },
  {
    id: 'reel-3',
    authorId: 'user-marcus',
    author: {
      id: 'user-marcus',
      username: 'marcus.thorne',
      displayName: 'Marcus Thorne',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-tree-branches-in-the-breeze-1188-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    caption: 'Street architecture photography in 60 seconds. Composition rules for brutalist lines 🏛️ #streetphotography #berlin #reels',
    tags: ['streetphotography', 'berlin', 'reels'],
    audioTrack: {
      title: 'Berlin Minimal Techno',
      artist: 'Marcus Thorne',
    },
    likesCount: 42100,
    likes: ['user-elena', 'user-maya'],
    commentsCount: 890,
    sharesCount: 7100,
    bookmarkedBy: ['user-elena'],
    createdAt: '2026-08-21T10:00:00.000Z',
  },
];

export const SEED_COMMENTS: Record<string, import('./types').Comment[]> = {
  'post-1': [
    {
      id: 'c1',
      postId: 'post-1',
      userId: 'user-aria',
      user: {
        username: 'aria.chen',
        displayName: 'Aria Chen',
        avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
        isVerified: true,
      },
      content: 'The caustic reflection on slide 2 is unreal! The synths we tuned for this fit like a glove 🔥',
      createdAt: '2026-08-21T15:10:00.000Z',
      likesCount: 24,
      likes: ['user-elena', 'user-marcus', 'user-kai'],
      replies: [
        {
          id: 'c1-r1',
          postId: 'post-1',
          userId: 'user-elena',
          user: {
            username: 'elena.vance',
            displayName: 'Elena Vance',
            avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
            isVerified: true,
          },
          content: 'Could not have done it without your frequencies @aria.chen! 💜',
          createdAt: '2026-08-21T15:20:00.000Z',
          likesCount: 8,
          likes: ['user-aria'],
        },
      ],
    },
    {
      id: 'c2',
      postId: 'post-1',
      userId: 'user-marcus',
      user: {
        username: 'marcus.thorne',
        displayName: 'Marcus Thorne',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
        isVerified: true,
      },
      content: 'Extraordinary depth. The chromatic aberration feels tactile rather than artificial. Stunning work Elena.',
      createdAt: '2026-08-21T15:15:00.000Z',
      likesCount: 16,
      likes: ['user-elena'],
    },
    {
      id: 'c3',
      postId: 'post-1',
      userId: 'user-chloe',
      user: {
        username: 'chloe.dubois',
        displayName: 'Chloé Dubois',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
        isVerified: true,
      },
      content: 'We need this projected on the runway for Fashion Week in Paris! 🔮',
      createdAt: '2026-08-21T15:30:00.000Z',
      likesCount: 12,
      likes: ['user-elena'],
    },
  ],
  'post-2': [
    {
      id: 'c4',
      postId: 'post-2',
      userId: 'user-elena',
      user: {
        username: 'elena.vance',
        displayName: 'Elena Vance',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
        isVerified: true,
      },
      content: 'The architectural composition here is masterclass Marcus. That contrast is razor sharp!',
      createdAt: '2026-08-21T13:30:00.000Z',
      likesCount: 32,
      likes: ['user-marcus'],
    },
  ],
};

export const SEED_STORIES: Story[] = [
  {
    id: 'story-elena',
    userId: 'user-elena',
    user: {
      id: 'user-elena',
      username: 'elena.vance',
      displayName: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    hasUnseen: true,
    lastUpdated: '2026-08-21T15:00:00.000Z',
    items: [
      {
        id: 'si-1',
        mediaUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1080&q=80',
        type: 'image',
        caption: 'Studio mornings with morning matcha & shader debugging 🍵💻',
        createdAt: '2026-08-21T14:00:00.000Z',
        expiresAt: '2026-08-22T14:00:00.000Z',
        viewsCount: 340,
        viewers: ['user-marcus', 'user-aria'],
      },
      {
        id: 'si-2',
        mediaUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1080&q=80',
        type: 'image',
        caption: 'New glass refraction experiment! Preview tonight 🔮',
        createdAt: '2026-08-21T15:00:00.000Z',
        expiresAt: '2026-08-22T15:00:00.000Z',
        viewsCount: 190,
        viewers: ['user-marcus'],
      },
    ],
  },
  {
    id: 'story-marcus',
    userId: 'user-marcus',
    user: {
      id: 'user-marcus',
      username: 'marcus.thorne',
      displayName: 'Marcus Thorne',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    hasUnseen: true,
    lastUpdated: '2026-08-21T14:30:00.000Z',
    items: [
      {
        id: 'si-3',
        mediaUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1080&q=80',
        type: 'image',
        caption: 'Darkroom prints ready for the gallery preview in Berlin 🎞️',
        createdAt: '2026-08-21T14:30:00.000Z',
        expiresAt: '2026-08-22T14:30:00.000Z',
        viewsCount: 620,
        viewers: ['user-elena', 'user-kai'],
      },
    ],
  },
  {
    id: 'story-aria',
    userId: 'user-aria',
    user: {
      id: 'user-aria',
      username: 'aria.chen',
      displayName: 'Aria Chen',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    hasUnseen: true,
    lastUpdated: '2026-08-21T15:10:00.000Z',
    items: [
      {
        id: 'si-4',
        mediaUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1080&q=80',
        type: 'image',
        caption: 'Oscilloscope patterns reacting to sub-bass 🔊⚡',
        createdAt: '2026-08-21T15:10:00.000Z',
        expiresAt: '2026-08-22T15:10:00.000Z',
        viewsCount: 410,
        viewers: ['user-elena'],
      },
    ],
  },
  {
    id: 'story-kai',
    userId: 'user-kai',
    user: {
      id: 'user-kai',
      username: 'kai.rivera',
      displayName: 'Kai Rivera',
      avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
      isVerified: false,
    },
    hasUnseen: false,
    lastUpdated: '2026-08-21T10:00:00.000Z',
    items: [
      {
        id: 'si-5',
        mediaUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
        type: 'image',
        caption: 'Rigging gear for tomorrow’s dawn patrol 🚤🌊',
        createdAt: '2026-08-21T10:00:00.000Z',
        expiresAt: '2026-08-22T10:00:00.000Z',
        viewsCount: 880,
        viewers: ['user-elena', 'user-marcus', 'user-aria'],
      },
    ],
  },
];

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-elena-marcus',
    participantIds: ['user-elena', 'user-marcus'],
    participants: [SEED_USERS[0], SEED_USERS[1]],
    lastMessage: {
      id: 'msg-1',
      conversationId: 'conv-elena-marcus',
      senderId: 'user-marcus',
      receiverId: 'user-elena',
      content: 'Let me know if you want high-res scans of the Berlin Brutalism series for your projection experiment!',
      createdAt: '2026-08-21T15:30:00.000Z',
      isRead: false,
    },
    unreadCount: 1,
    updatedAt: '2026-08-21T15:30:00.000Z',
  },
  {
    id: 'conv-elena-aria',
    participantIds: ['user-elena', 'user-aria'],
    participants: [SEED_USERS[0], SEED_USERS[2]],
    lastMessage: {
      id: 'msg-2',
      conversationId: 'conv-elena-aria',
      senderId: 'user-elena',
      receiverId: 'user-aria',
      content: 'Just posted the new carousel with your soundtrack! The feedback is amazing 🎉',
      createdAt: '2026-08-21T15:20:00.000Z',
      isRead: true,
    },
    unreadCount: 0,
    updatedAt: '2026-08-21T15:20:00.000Z',
  },
  {
    id: 'conv-elena-kai',
    participantIds: ['user-elena', 'user-kai'],
    participants: [SEED_USERS[0], SEED_USERS[3]],
    lastMessage: {
      id: 'msg-3',
      conversationId: 'conv-elena-kai',
      senderId: 'user-kai',
      receiverId: 'user-elena',
      content: 'Sent you a voice message about the documentary score.',
      isAudioVoiceNote: true,
      audioDuration: 24,
      createdAt: '2026-08-21T12:00:00.000Z',
      isRead: true,
    },
    unreadCount: 0,
    updatedAt: '2026-08-21T12:00:00.000Z',
  },
  {
    id: 'group-lumira-creators',
    isGroup: true,
    groupName: 'Lumira Creators Collective 🚀',
    groupAvatarUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80',
    participantIds: ['user-admin', 'user-elena', 'user-marcus', 'user-aria', 'user-kai'],
    participants: [SEED_USERS[0], SEED_USERS[1], SEED_USERS[2], SEED_USERS[3]],
    lastMessage: {
      id: 'msg-g2',
      conversationId: 'group-lumira-creators',
      senderId: 'user-marcus',
      receiverId: 'group-lumira-creators',
      content: 'Dropping the new 3D architectural renders today!',
      createdAt: '2026-08-21T16:15:00.000Z',
      isRead: true,
    },
    unreadCount: 0,
    updatedAt: '2026-08-21T16:15:00.000Z',
  },
];

export const SEED_MESSAGES: Record<string, import('./types').Message[]> = {
  'group-lumira-creators': [
    {
      id: 'msg-g1',
      conversationId: 'group-lumira-creators',
      senderId: 'user-aria',
      receiverId: 'group-lumira-creators',
      content: 'Welcome everyone! Let us share our upcoming visual projects and collaborations here 🎨',
      createdAt: '2026-08-21T16:00:00.000Z',
      isRead: true,
      reactions: [{ userId: 'user-elena', emoji: '❤️' }, { userId: 'user-admin', emoji: '🚀' }],
    },
    {
      id: 'msg-g2',
      conversationId: 'group-lumira-creators',
      senderId: 'user-marcus',
      receiverId: 'group-lumira-creators',
      content: 'Dropping the new 3D architectural renders today!',
      createdAt: '2026-08-21T16:15:00.000Z',
      isRead: true,
      reactions: [{ userId: 'user-kai', emoji: '🔥' }],
    },
  ],
  'conv-elena-marcus': [
    {
      id: 'm-101',
      conversationId: 'conv-elena-marcus',
      senderId: 'user-elena',
      receiverId: 'user-marcus',
      content: 'Hey Marcus, saw your new Berlin series. The lighting is pristine!',
      createdAt: '2026-08-21T14:30:00.000Z',
      isRead: true,
    },
    {
      id: 'm-102',
      conversationId: 'conv-elena-marcus',
      senderId: 'user-marcus',
      receiverId: 'user-elena',
      content: 'Thanks Elena! That morning fog made all the difference. I was thinking of mapping your generative glass shaders over architectural facades.',
      createdAt: '2026-08-21T15:00:00.000Z',
      isRead: true,
      reactions: [{ userId: 'user-elena', emoji: '🔥' }],
    },
    {
      id: 'm-103',
      conversationId: 'conv-elena-marcus',
      senderId: 'user-marcus',
      receiverId: 'user-elena',
      content: 'Let me know if you want high-res scans of the Berlin Brutalism series for your projection experiment!',
      createdAt: '2026-08-21T15:30:00.000Z',
      isRead: false,
    },
  ],
  'conv-elena-aria': [
    {
      id: 'm-201',
      conversationId: 'conv-elena-aria',
      senderId: 'user-aria',
      receiverId: 'user-elena',
      content: 'Sent you the master FLAC file for the ambient mix!',
      createdAt: '2026-08-21T14:00:00.000Z',
      isRead: true,
    },
    {
      id: 'm-202',
      conversationId: 'conv-elena-aria',
      senderId: 'user-elena',
      receiverId: 'user-aria',
      content: 'Just posted the new carousel with your soundtrack! The feedback is amazing 🎉',
      createdAt: '2026-08-21T15:20:00.000Z',
      isRead: true,
      reactions: [{ userId: 'user-aria', emoji: '❤️' }],
    },
  ],
};

export const SEED_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'user-elena',
    actorId: 'user-aria',
    actor: {
      id: 'user-aria',
      username: 'aria.chen',
      displayName: 'Aria Chen',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    type: 'comment',
    postId: 'post-1',
    postThumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80',
    commentText: 'The caustic reflection on slide 2 is unreal! The synths we tuned for this fit like a glove 🔥',
    isRead: false,
    createdAt: '2026-08-21T15:10:00.000Z',
  },
  {
    id: 'notif-2',
    userId: 'user-elena',
    actorId: 'user-marcus',
    actor: {
      id: 'user-marcus',
      username: 'marcus.thorne',
      displayName: 'Marcus Thorne',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    type: 'like_post',
    postId: 'post-1',
    postThumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80',
    isRead: false,
    createdAt: '2026-08-21T15:15:00.000Z',
  },
  {
    id: 'notif-3',
    userId: 'user-elena',
    actorId: 'user-maya',
    actor: {
      id: 'user-maya',
      username: 'maya.lin',
      displayName: 'Maya Lin',
      avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    type: 'follow',
    isRead: true,
    createdAt: '2026-08-21T12:00:00.000Z',
  },
  {
    id: 'notif-4',
    userId: 'user-elena',
    actorId: 'user-chloe',
    actor: {
      id: 'user-chloe',
      username: 'chloe.dubois',
      displayName: 'Chloé Dubois',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    type: 'comment',
    postId: 'post-1',
    postThumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80',
    commentText: 'We need this projected on the runway for Fashion Week in Paris! 🔮',
    isRead: true,
    createdAt: '2026-08-21T15:30:00.000Z',
  },
];

export const POPULAR_SONGS = [
  {
    title: 'Disconnect',
    artist: 'Becky Hill, Chase & Status',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=300&q=80',
  },
  {
    title: 'Neural Waves (Ambient Mix)',
    artist: 'Aria Chen',
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=300&q=80',
  },
  {
    title: 'Midnight City',
    artist: 'M83',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=300&q=80',
  },
  {
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=300&q=80',
  },
  {
    title: 'As It Was',
    artist: 'Harry Styles',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=300&q=80',
  },
  {
    title: 'Levitating',
    artist: 'Dua Lipa',
    coverUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=300&q=80',
  },
  {
    title: 'Starboy',
    artist: 'The Weeknd ft. Daft Punk',
    coverUrl: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?auto=format&fit=crop&w=300&q=80',
  },
];

export const SEED_NOTES: import('./types').UserNote[] = [
  {
    id: 'note-aria',
    userId: 'user-aria',
    user: SEED_USERS[1],
    text: 'REDIRECT if...',
    song: {
      title: 'Disconnect',
      artist: 'Becky Hill, Chase & Status',
      coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=300&q=80',
    },
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'note-marcus',
    userId: 'user-marcus',
    user: SEED_USERS[0],
    text: 'New reel 🎥',
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'note-kai',
    userId: 'user-kai',
    user: SEED_USERS[2],
    text: 'Join the PBB Angels IG Channel 🪽🤍',
    song: {
      title: 'Midnight City',
      artist: 'M83',
      coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=300&q=80',
    },
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'note-maya',
    userId: 'user-maya',
    user: SEED_USERS[3],
    text: 'Designing in Tokyo ✨',
    song: {
      title: 'Neural Waves (Ambient Mix)',
      artist: 'Aria Chen',
    },
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const SEED_INSTANTS: InstantItem[] = [
  {
    id: 'instant-elena-1',
    creatorId: 'user-elena',
    creator: {
      id: 'user-elena',
      username: 'elena.vance',
      displayName: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    mediaUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1080&q=80',
    mediaType: 'image',
    filterId: 'aurora',
    filterIntensity: 90,
    adjustments: {
      brightness: 105,
      contrast: 110,
      saturation: 120,
      exposure: 0,
      temperature: 5,
      tint: 0,
      highlights: 0,
      shadows: 0,
      sharpness: 20,
      clarity: 15,
      fade: 0,
      vignette: 15,
      grain: 10,
      blur: 0,
      zoom: 1,
      panX: 0,
      panY: 0,
      rotate: 0,
      flipH: false,
      flipV: false,
      straighten: 0,
      aspectRatio: 'free',
    },
    textOverlays: [
      {
        id: 't1',
        text: 'Tokyo Studio Glow ✨',
        x: 50,
        y: 82,
        fontFamily: 'sans',
        fontSize: 22,
        color: '#ffffff',
        backgroundColor: 'rgba(0, 0, 0, 0.45)',
        bold: true,
        align: 'center',
        shadow: true,
      },
    ],
    stickers: [
      {
        id: 's1',
        type: 'location',
        content: '📍 Roppongi Hills, Tokyo',
        x: 50,
        y: 16,
        scale: 1,
        rotation: 0,
      },
    ],
    attachedMusic: {
      trackId: 'track-midnight-cityscape',
      provider: 'demo',
      providerTrackId: 'demo-001',
      title: 'Midnight Cityscape',
      artist: 'Aria Chen',
      album: 'Neon Genesis',
      coverImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80',
      duration: 15,
      audioSource: 'synth-midnight',
      startTime: 0,
    },
    caption: 'Reflections from the high-res 3D simulation session',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1h ago
    expiresAt: new Date(Date.now() + 23 * 60 * 60 * 1000).toISOString(), // 23h left
    visibility: 'Everyone',
    reactions: [
      { userId: 'user-marcus', emoji: '🔥', createdAt: new Date().toISOString() },
      { userId: 'user-aria', emoji: '❤️', createdAt: new Date().toISOString() },
    ],
    viewers: ['user-marcus', 'user-aria', 'user-kai'],
    viewsCount: 148,
  },
  {
    id: 'instant-marcus-1',
    creatorId: 'user-marcus',
    creator: {
      id: 'user-marcus',
      username: 'marcus.thorne',
      displayName: 'Marcus Thorne',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    mediaUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1080&q=80',
    mediaType: 'image',
    filterId: 'noir',
    filterIntensity: 100,
    adjustments: {
      brightness: 95,
      contrast: 130,
      saturation: 0,
      exposure: 0,
      temperature: 0,
      tint: 0,
      highlights: 0,
      shadows: 0,
      sharpness: 40,
      clarity: 30,
      fade: 0,
      vignette: 25,
      grain: 20,
      blur: 0,
      zoom: 1,
      panX: 0,
      panY: 0,
      rotate: 0,
      flipH: false,
      flipV: false,
      straighten: 0,
      aspectRatio: 'free',
    },
    textOverlays: [
      {
        id: 't2',
        text: 'Shadows & Angles 🏛️',
        x: 50,
        y: 85,
        fontFamily: 'serif',
        fontSize: 20,
        color: '#ffffff',
        backgroundColor: 'rgba(15, 23, 42, 0.7)',
        bold: true,
        align: 'center',
      },
    ],
    stickers: [
      {
        id: 's2',
        type: 'time',
        content: '⏰ 06:45 AM',
        x: 24,
        y: 15,
        scale: 1,
      },
    ],
    caption: 'Brutalist dawn in Berlin',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), // 5h ago
    expiresAt: new Date(Date.now() + 19 * 60 * 60 * 1000).toISOString(), // 19h left
    visibility: 'Everyone',
    reactions: [
      { userId: 'user-elena', emoji: '👏', createdAt: new Date().toISOString() },
      { userId: 'user-maya', emoji: '❤️', createdAt: new Date().toISOString() },
    ],
    viewers: ['user-elena', 'user-maya'],
    viewsCount: 230,
  },
  {
    id: 'instant-aria-1',
    creatorId: 'user-aria',
    creator: {
      id: 'user-aria',
      username: 'aria.chen',
      displayName: 'Aria Chen',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    mediaUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1080&q=80',
    mediaType: 'image',
    filterId: 'cyber',
    filterIntensity: 85,
    adjustments: {
      brightness: 100,
      contrast: 115,
      saturation: 130,
      exposure: 0,
      temperature: -15,
      tint: 10,
      highlights: 0,
      shadows: 0,
      sharpness: 10,
      clarity: 10,
      fade: 0,
      vignette: 10,
      grain: 5,
      blur: 0,
      zoom: 1,
      panX: 0,
      panY: 0,
      rotate: 0,
      flipH: false,
      flipV: false,
      straighten: 0,
      aspectRatio: 'free',
    },
    textOverlays: [
      {
        id: 't3',
        text: 'Analog Synth Calibration ⚡',
        x: 50,
        y: 84,
        fontFamily: 'mono',
        fontSize: 18,
        color: '#38bdf8',
        backgroundColor: 'rgba(2, 6, 23, 0.8)',
        bold: true,
        align: 'center',
      },
    ],
    stickers: [
      {
        id: 's3',
        type: 'hashtag',
        content: '#synthwave',
        x: 75,
        y: 18,
        scale: 1,
      },
    ],
    caption: 'Oscilloscope harmonics in the lab',
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 14 * 60 * 60 * 1000).toISOString(), // 14h left
    visibility: 'Everyone',
    reactions: [
      { userId: 'user-elena', emoji: '⚡', createdAt: new Date().toISOString() },
    ],
    viewers: ['user-elena', 'user-marcus'],
    viewsCount: 312,
  },
  {
    id: 'instant-kai-1',
    creatorId: 'user-kai',
    creator: {
      id: 'user-kai',
      username: 'kai.rivera',
      displayName: 'Kai Rivera',
      avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
      isVerified: false,
    },
    mediaUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1080&q=80',
    mediaType: 'image',
    filterId: 'golden',
    filterIntensity: 90,
    textOverlays: [
      {
        id: 't4',
        text: 'Nazaré Atlantic Swell 🌊',
        x: 50,
        y: 80,
        fontFamily: 'sans',
        fontSize: 22,
        color: '#ffffff',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        bold: true,
        align: 'center',
      },
    ],
    stickers: [
      {
        id: 's4',
        type: 'location',
        content: '📍 Nazaré Beach, Portugal',
        x: 50,
        y: 16,
        scale: 1,
      },
    ],
    caption: 'Atlantic sunset waves',
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(), // 8h left
    visibility: 'Close Friends',
    reactions: [
      { userId: 'user-marcus', emoji: '🔥', createdAt: new Date().toISOString() },
    ],
    viewers: ['user-elena', 'user-marcus', 'user-aria'],
    viewsCount: 420,
  },
  {
    id: 'instant-maya-1',
    creatorId: 'user-maya',
    creator: {
      id: 'user-maya',
      username: 'maya.lin',
      displayName: 'Maya Lin',
      avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    mediaUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1080&q=80',
    mediaType: 'image',
    filterId: 'velvet',
    filterIntensity: 80,
    textOverlays: [
      {
        id: 't5',
        text: 'Copenhagen Ceramic Studio 🏺',
        x: 50,
        y: 85,
        fontFamily: 'serif',
        fontSize: 18,
        color: '#ffffff',
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        bold: true,
        align: 'center',
      },
    ],
    caption: 'Handcrafted volcanic sand glaze piece',
    createdAt: new Date(Date.now() - 21 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(), // 3h left
    visibility: 'Everyone',
    reactions: [
      { userId: 'user-elena', emoji: '❤️', createdAt: new Date().toISOString() },
    ],
    viewers: ['user-elena', 'user-kai'],
    viewsCount: 189,
  },
  // Previous Instants from earlier this week for the "THIS WEEK" section
  {
    id: 'instant-past-1',
    creatorId: 'user-elena',
    creator: {
      id: 'user-elena',
      username: 'elena.vance',
      displayName: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    mediaUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1080&q=80',
    mediaType: 'image',
    filterId: 'aurora',
    caption: 'Prism caustics in dark room',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    expiresAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    visibility: 'Everyone',
    reactions: [
      { userId: 'user-marcus', emoji: '🔥', createdAt: new Date().toISOString() },
      { userId: 'user-aria', emoji: '❤️', createdAt: new Date().toISOString() },
    ],
    viewers: ['user-marcus', 'user-aria'],
    viewsCount: 395,
  },
  {
    id: 'instant-past-2',
    creatorId: 'user-marcus',
    creator: {
      id: 'user-marcus',
      username: 'marcus.thorne',
      displayName: 'Marcus Thorne',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      isVerified: true,
    },
    mediaUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1080&q=80',
    mediaType: 'image',
    filterId: 'noir',
    caption: 'Minimalist concrete stair geometry',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), // 4 days ago
    expiresAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    visibility: 'Everyone',
    reactions: [
      { userId: 'user-elena', emoji: '❤️', createdAt: new Date().toISOString() },
    ],
    viewers: ['user-elena', 'user-kai'],
    viewsCount: 512,
  },
];
